### ISSUE TITLE
api key and secret is all in uppercase

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#11]
Based on our discussion the api key and secret in portal need to be lowered cased

**Comment by dendisuhubdy** [comment]
<img width="1150" alt="Screen Shot 2021-06-21 at 12 27 32" src="https://user-images.githubusercontent.com/4477337/122711645-b478c480-d28c-11eb-9305-b8c546f739d1.png">

we fixed this, thanks @welly87
