### ISSUE TITLE
inconsistent documentation for sample code

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#12]
![image](https://user-images.githubusercontent.com/242694/121325154-91205200-c93b-11eb-932a-b3a58820515d.png)

need to update the docs to be in sync with sample code.

**Comment by welly87** [comment]
the tilte is GET but the code sample is POST

![image](https://user-images.githubusercontent.com/242694/121325389-c331b400-c93b-11eb-8a41-9a32b97962a4.png)

**Comment by dendisuhubdy** [comment]
thanks for the headsup @welly87
