### ISSUE TITLE
change the rest model in wss

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#13]
i think we can use single authentication for the whole session, as websocket is stateful connection. so it should remember the previous authentication and not treat that as http rest stateless call.

![image](https://user-images.githubusercontent.com/242694/121330294-11e14d00-c940-11eb-93d6-b7a0010ad2c2.png)

we can see the good example from deribit like [this](https://docs.deribit.com/#authentication-2). even we don't need to go using json rpc as that's bloated the websocket body

**Comment by welly87** [comment]
we can just spesify the message type id so we don't use string key value pair in json. so it more lightweight. we can specify the message type id and correlation as the header that need to be send in the message header format.

**Comment by dendisuhubdy** [comment]
no thanks @welly87
