### ISSUE TITLE
readme for python rest sdk for dev and user

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#18]
hi @mohammedaugie13 

currently there's no readme for python rest sdk. also if possible need to give the pip install spesification from PyPI

**Comment by dendisuhubdy** [comment]
@welly87 we did provide it here https://github.com/bitwyre/sdk/tree/develop/REST/python

**Comment by welly87** [comment]
it's empty

![image](https://user-images.githubusercontent.com/242694/122712916-0589b800-d28f-11eb-95c7-73247cbcf1c8.png)
