### ISSUE TITLE
dev pip install requirements error for hmac and hashlib

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#19]
hi @mohammedaugie13 

i found error when doing pip install with conda in python3.8 env. I think it trying to load python2 version? 

![image](https://user-images.githubusercontent.com/242694/122486519-6d2bd300-d003-11eb-9b16-4eed6954bf9b.png)

i try another python3 environment but still the same.

is there any workaround on python3 for these library?

cheers

**Comment by welly87** [comment]
i think we can just remove the libs from the requirements-dev.txt? as it's already handled by the python3.8. 

the IDE is yelling because it's not installed. false alarm

![image](https://user-images.githubusercontent.com/242694/122486983-576add80-d004-11eb-9813-ca9502701fef.png)

**Comment by dendisuhubdy** [comment]
@welly87 thanks for clarifying that, no we need to keep those for internal purposes
