### ISSUE TITLE
python sdk structure 

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#20]
hi @mohammedaugie13 

currently it's hard to find the class as it's in init file. any reason why we are not create separate file for these class?

![telegram-cloud-photo-size-5-6224349240990215091-y](https://user-images.githubusercontent.com/242694/122486677-c0058a80-d003-11eb-87f4-69935f36c1ce.jpg)

**Comment by dendisuhubdy** [comment]
It's intentional @welly87
