### ISSUE TITLE
failed running sdk from pycharm test

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#21]
hi @mohammedaugie13 

i can't run the test from pycharm. 

![image](https://user-images.githubusercontent.com/242694/122487171-d102cb80-d004-11eb-948a-bfe131b86453.png)

it's scream nose is not installed. 

![image](https://user-images.githubusercontent.com/242694/122487215-ebd54000-d004-11eb-8dee-3c882ebf20fc.png)

could you please suggest which environment i should run this? any spesific tools or details you can share?

**Comment by dendisuhubdy** [comment]
@welly87 that's our internal environment for the tests, we should probably get rid of them @mohammedaugie13
