### ISSUE TITLE
api key revoke

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#22]
@mohammedaugie13 

i try to copy the required files into the new solution. it's running now but seems my API key is revoked. 

![image](https://user-images.githubusercontent.com/242694/122487862-6f436100-d006-11eb-87b6-47c66c09f34a.png)

is there any revoke policy that i don't know? or this only happened on the dev environment?

thanks

**Comment by welly87** [comment]
@mohammedaugie13 @dendisuhubdy seems that my old account is not working anymore... do i need to reset or create new account for this? 

![image](https://user-images.githubusercontent.com/242694/122488011-c77a6300-d006-11eb-8082-697ff4de6db4.png)

**Comment by welly87** [comment]
i try to register but it's still loading .. and i don't find any notification in my email.

![image](https://user-images.githubusercontent.com/242694/122488121-03152d00-d007-11eb-86f8-ecba67d8fe85.png)

am i missing something?

**Comment by welly87** [comment]
after around 15s it's sending an email but there's notifcation on the page..  it's just showing this again

![image](https://user-images.githubusercontent.com/242694/122488230-36f05280-d007-11eb-9695-c27897027e48.png)

**Comment by welly87** [comment]
not sure how i can verify this code? i hope there's a link that i can click then activate?

![image](https://user-images.githubusercontent.com/242694/122488261-4d96a980-d007-11eb-9614-c0b8d1fb0991.png)

**Comment by welly87** [comment]
i try to login but it's kicking me out with this message

![image](https://user-images.githubusercontent.com/242694/122488324-71f28600-d007-11eb-8cce-e686488148da.png)

**Comment by welly87** [comment]
i try to sign up again but it's failed because of duplication
![image](https://user-images.githubusercontent.com/242694/122488407-9d757080-d007-11eb-95e9-67bc8afc9e29.png)

**Comment by welly87** [comment]
i'm finally trying forgot password.. it's still take around 10s to complete

![image](https://user-images.githubusercontent.com/242694/122488514-cdbd0f00-d007-11eb-8521-bd748584f35f.png)

finally i got the email after 15s

![image](https://user-images.githubusercontent.com/242694/122488553-e5949300-d007-11eb-98a5-c5830e8130bf.png)

but when i click the link.. it's 404

![image](https://user-images.githubusercontent.com/242694/122488592-fb09bd00-d007-11eb-8404-4e76a172397c.png)

**Comment by welly87** [comment]
i also try your provided api key.. but still revoked.

![image](https://user-images.githubusercontent.com/242694/122488721-402def00-d008-11eb-89ab-3c4bbc60f433.png)

**Comment by welly87** [comment]
i try creating new account with another email

![image](https://user-images.githubusercontent.com/242694/122488864-9864f100-d008-11eb-9c68-8600da00b364.png)


this time it's doesn't stop loading but sending the email.. but i can't find the page to verify.. back to the previous state.

![image](https://user-images.githubusercontent.com/242694/122488923-bcc0cd80-d008-11eb-99f3-a5cc4ba6147a.png)

thought?

**Comment by dendisuhubdy** [comment]
<img width="1258" alt="Screen Shot 2021-06-21 at 09 08 38" src="https://user-images.githubusercontent.com/4477337/122711253-14bb3680-d28c-11eb-9fac-fe114e3dec3b.png">
<img width="1150" alt="Screen Shot 2021-06-21 at 12 27 32" src="https://user-images.githubusercontent.com/4477337/122711265-1b49ae00-d28c-11eb-82d2-0ae4cb94b571.png">
<img width="1657" alt="Screen Shot 2021-06-21 at 12 27 28" src="https://user-images.githubusercontent.com/4477337/122711266-1be24480-d28c-11eb-9173-bc5e5d3bf75c.png">
<img width="1668" alt="Screen Shot 2021-06-21 at 12 27 15" src="https://user-images.githubusercontent.com/4477337/122711269-1c7adb00-d28c-11eb-9039-a5307c0c2253.png">
<img width="1663" alt="Screen Shot 2021-06-21 at 12 27 02" src="https://user-images.githubusercontent.com/4477337/122711270-1d137180-d28c-11eb-980c-eded9cb1dae1.png">
<img width="1666" alt="Screen Shot 2021-06-21 at 12 26 32" src="https://user-images.githubusercontent.com/4477337/122711273-1dac0800-d28c-11eb-8185-bfbfefce58ed.png">
<img width="1659" alt="Screen Shot 2021-06-21 at 12 26 15" src="https://user-images.githubusercontent.com/4477337/122711274-1dac0800-d28c-11eb-834d-555c2f334fb2.png">
<img width="1662" alt="Screen Shot 2021-06-21 at 12 26 06" src="https://user-images.githubusercontent.com/4477337/122711275-1e449e80-d28c-11eb-924b-9deb0c3b7d9c.png">
<img width="1409" alt="Screen Shot 2021-06-21 at 12 25 50" src="https://user-images.githubusercontent.com/4477337/122711281-1edd3500-d28c-11eb-9d9b-2f276f5770c9.png">
<img width="1652" alt="Screen Shot 2021-06-21 at 12 25 19" src="https://user-images.githubusercontent.com/4477337/122711283-1f75cb80-d28c-11eb-8fcb-68fc3f17adee.png">
<img width="1664" alt="Screen Shot 2021-06-21 at 12 25 11" src="https://user-images.githubusercontent.com/4477337/122711286-200e6200-d28c-11eb-9734-656004b4bdae.png">
<img width="1398" alt="Screen Shot 2021-06-21 at 12 28 06" src="https://user-images.githubusercontent.com/4477337/122711314-2a306080-d28c-11eb-926d-b97f02ed1b70.png">
<img width="1402" alt="Screen Shot 2021-06-21 at 12 28 03" src="https://user-images.githubusercontent.com/4477337/122711319-2c92ba80-d28c-11eb-8d6f-3db011911d20.png">

**Comment by dendisuhubdy** [comment]
no api revoked unintentionally, we do database wipes during development
