### ISSUE TITLE
docs sometimes is not loaded

### ISSUE THREAD

**Issue by welly87** [bitwyre/sdk#8]
sometimes when opening https://docs.bitwyre.com/ it's very slow and sometimes just showing a blank page. 

i try multiple browser and connection, but still the same.

**Comment by dendisuhubdy** [comment]
woops! Fixing @welly87

**Comment by dendisuhubdy** [comment]
@welly87 please check
- https://docs.bitwyre.net 
- https://docs.bitwyre.id
- https://docs.bitwyre.cc

just in case https://docs.bitwyre.com is down

**Comment by dendisuhubdy** [comment]
<img width="1676" alt="Screen Shot 2021-06-21 at 12 38 22" src="https://user-images.githubusercontent.com/4477337/122712119-9bbcde80-d28d-11eb-875d-11eed7ee0ab8.png">
<img width="1673" alt="Screen Shot 2021-06-21 at 12 38 16" src="https://user-images.githubusercontent.com/4477337/122712134-a0819280-d28d-11eb-9252-4a6f17ed308e.png">
<img width="1666" alt="Screen Shot 2021-06-21 at 12 38 12" src="https://user-images.githubusercontent.com/4477337/122712138-a1b2bf80-d28d-11eb-987d-9f0131042b4d.png">
